name: Generate API Docs

on:
  push:
    branches:
      - LP-156-Frontend-Refactor # This is temporary and will be replaced by `app` once the refactor is complete
  workflow_dispatch: # For manual triggering

jobs:
  generate-api-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          ref: LP-156-Frontend-Refactor # This is temporary and will be replaced by `app` once the refactor is complete
          path: app

      - name: Checkout docs branch
        uses: actions/checkout@v3
        with:
          ref: docs
          clean: false
          path: docs

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.4'

      - name: Get dependencies
        working-directory: app
        run: flutter pub get
        
      - name: Generate API Docs
        working-directory: app
        run: dart doc
      
      - name: Clear old documentation in /app subdir
        run: |
          rm -rf docs/app/*
          mkdir -p docs/app

      - name: Copy generated docs to /app subdir
        run: | 
          cp -R app/doc/api/* docs/app/
        
      - name: Push new documentation to docs branch
        working-directory: docs
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions-bot@users.noreply.github.com"
          git add -A
          git commit -m "GitHub Actions - Update client-side API documentation to ${{ github.sha }}"
          git push